//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationmovies
{
    using System;
    using System.Collections.Generic;
    
    public partial class NeeranjMovie
    {
        public int MovID { get; set; }
        public string MovName { get; set; }
        public Nullable<System.DateTime> RealaseDate { get; set; }
    }
}
